server:
  port: 8081

spring:
  application:
    name: qlexpress-web-test
  profiles:
    active: dev

logging:
  config: classpath:log/logback.xml
  level:
    root: INFO
    com.ql.qlexpress.web: DEBUG
