server:
  port: 8080

spring:
  application:
    name: qlexpress-web
  profiles:
    active: dev

logging:
  config: classpath:log/logback-spring.xml
  level:
    root: INFO
    com.ql.qlexpress.web: DEBUG
